---
# tasks file for roles/selinux
- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: "CCE-80445-0, Ensure mcstrans is removed"
  package:
    name: mcstrans
    state: absent
#  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags:
    - CCE-80445-0

- name: Ensure setroubleshoot is removed
  package:
    name: setroubleshoot
    state: absent
#  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags:
    - CCE-80444-3

- name: Ensure SELinux Not Disabled in /etc/default/grub
  replace:
    dest: /etc/default/grub
    regexp: selinux=0
#  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags:
    - CCE-26961-3

- name: XCCDF Value var_selinux_policy_name # promote to variable
  set_fact:
    var_selinux_policy_name: !!str targeted
  tags:
    - always

- name: Configure SELinux Policy
  lineinfile:
    path: /etc/sysconfig/selinux
    regexp: ^SELINUXTYPE=
    line: SELINUXTYPE={{ var_selinux_policy_name }}
    create: true
#  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags:
    - CCE-27279-9

#- name: Ensure No Daemons are Unconfined by SELinux
#$ sudo ps -eZ | egrep "initrc" | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'

- name: XCCDF Value var_selinux_state # promote to variable
  set_fact:
    var_selinux_state: !!str enforcing
  tags:
    - always

- name: Ensure SELinux State is Enforcing
  lineinfile:
    path: /etc/sysconfig/selinux
    regexp: ^SELINUX=
    line: SELINUX={{ var_selinux_state }}
    create: true
#  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags:
    - CCE-27334-2