---
# Ansible Playbook - check Security Compliance on Linux servers 
- name: "Playing with Ansible"
  hosts: servers
  port: 22
  gather_facts: true
  vars:
    sec001: "{{ lookup('csvfile', 'sec001 file=/Users/gamma/_ansible/securitycompliance/files/index.csv delimiter=;') }}"
    sec002: "{{ lookup('csvfile', 'sec002 file=/Users/gamma/_ansible/securitycompliance/files/index.csv delimiter=;') }}"
    sec003: "{{ lookup('csvfile', 'sec003 file=/Users/gamma/_ansible/securitycompliance/files/index.csv delimiter=;') }}"
  tasks:
  - name: check if index.csv file exists
    local_action: stat path=/Users/gamma/_ansible/securitycompliance/files/index.csv
    register: index_csv_file
  - debug:
      msg: "The file index.csv exist? = {{ index_csv_file.stat.exists }} "
  
  - name: "{{ sec001 }}"
    # SELINUX | CIS | Identifier des controles SELinux qui sont dans le CIS Linux RH7
    include_role:
      name: sec001
    when: >
      (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
    tags:
      - cis
      - RedHat7
      - selinux

  - name: "{{ sec002 }}"
      # SELINUX | NIST-800 | Identifier des controles NIST-800-171-cui Linux RH7
    include_role:
      name: sec002
    tags:
      - rhel7-role-nist-800-171-cui
      - nist-800
      - noncis
      - RedHat7
    when: >
      (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - name: "{{ sec003 }}"
      # POSIX capabilities | Linux RH7
    include_role:
      name: colsecinfo
    tags:
      - RedHat7
      - LinEnum
    when: >
      (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - name: "{{ rh8-security-features }}"
      # role rh8-security-features: Security for RHEL8 | Linux RH8
    include_role:
      name: rh8-security-features
    tags:
      - RedHat8
      - RHEL8
    when: >
      (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")