---
# Ansible Playbook - check Security Compliance on Linux servers 
- name: "Playing with Ansible"
  hosts: esxcentos
  port: 22
  gather_facts: true
  vars:
    sec001: "{{ lookup('csvfile', 'sec001 file=/Users/gamma/_ansible/securitycompliance/files/index.csv delimiter=;') }}"
    sec002: "{{ lookup('csvfile', 'sec002 file=/Users/gamma/_ansible/securitycompliance/files/index.csv delimiter=;') }}"
    sec003: "{{ lookup('csvfile', 'sec003 file=/Users/gamma/_ansible/securitycompliance/files/index.csv delimiter=;') }}"
  tasks:
  - name: "{{ sec001 }}"
    include_role:
      name: sec001

  - name: "{{ sec002 }}"
    include_role:
      name: sec002

  - name: "{{ sec003 }}"
    include_role:
      name: sec003



# Ancienne configuration
#  roles:
#  - ctrlselinux
#  - ctrlnist800
#  - checkotherperm
#  - colsecinfo