---
# Ansible Playbook - check Security Compliance on Linux servers 
- name: "Playing with Ansible"
  hosts: esxcentos
  port: 22
  gather_facts: true
  roles:
  - ctrlselinux
  - ctrlnist800
  - checkotherperm
  - colsecinfo