---
- name: Install the fapolicyd package
  yum:
    name: "fapolicyd"
    state: present
    update_cache: true
  become: true
  register: yum_fapolicyd_output
- debug: var=yum_fapolicyd_output.msg
#----------------------------------
- name: Enabling fapolicyd service
  service:
    name: fapolicyd
    enabled: yes
    state: restarted
  register: service_fapolicyd_output
- debug: var=service_fapolicyd_output.state
#----------------------------------
...