---
# tasks file for roles/rh8-security-features
# display the STATUS of var_check_mode
- debug:
    msg: 
    - "### STATUS ### --- var_check_mode --- ### STATUS ###"
    - "STATUS = {{ var_check_mode }}"
    - "------------------------------------------"
    - "if TRUE = CHECK ONLY !"
    - "D A N G E R -> if FALSE = APPLY CONFIGURATION -> D A N G E R"
    - "change the value into the file: roles/rh8-security-features/defaults/main.yml"
    - "##########################################"
#-------------------------------------------
- name: obtain OS version
  shell: cat /etc/centos-release
  register: result_os_version
- name: print OS version
  debug: var=result_os_version.stdout
 #-------------------------------------------
- name: fapolicyd | CONFIGURING APPLICATION WHITELISTS
  import_tasks: fapolicyd.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_fapolicyd
    - RedHat8
    - rh8-security-features
#-------------------------------------------
- name: crypto-policies | SYSTEM-WIDE CRYPTOGRAPHIC POLICIES
  import_tasks: crypto-policies.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_crypto-policies
    - RedHat8
    - rh8-security-features
#-------------------------------------------
- name: firewalld | CONFIGURING FIREWALLS
  import_tasks: firewalld.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_firewalld
    - RedHat8
    - rh8-security-features
#-------------------------------------------
- name: selinux | CONFIGURING SELINUX
  import_tasks: selinux.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_selinux
    - RedHat8
    - rh8-security-features
#------------------------------------------- 
- name: LinEnum | CONFIGURING File Permissions and Masks
  import_tasks: linenum.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_linenum
    - RedHat8
    - rh8-security-features
  ignore_errors: yes
#-------------------------------------------
- name: auditd | CONFIGURING AUDITD
  import_tasks: auditd.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_auditd
    - RedHat8
    - rh8-security-features
#-------------------------------------------
- name: ObsoleteServices | Verify Obsolete Services
  import_tasks: obsolete-services.yml
  check_mode: "{{ var_check_mode }}"
  tags:
    - config_ObsoleteServices
    - RedHat8
    - rh8-security-features
#-------------------------------------------
- name: Generate report 
  template: 
    src: report.j2 
    dest: report.out
    owner: ransible
    group: ransible
    mode: 0640
...