---
# tasks file for roles/rh8-security-features
# variable var_go_execute = True (roles/rh8-security-features/defaults/main.yml)
- name: obtain OS version
  shell: cat /etc/centos-release
  register: result
- name: print OS version
  debug: var=result.stdout
 #-------------------------------------------
- name: fapolicyd | CONFIGURING APPLICATION WHITELISTS
  import_tasks: fapolicyd.yml
  when: 
    - var_go_execute
  tags:
    - config_fapolicyd
    - CentOs8
    - rh8-security-features
#-------------------------------------------
- name: crypto-policies | SYSTEM-WIDE CRYPTOGRAPHIC POLICIES
  import_tasks: crypto-policies.yml
  when: 
    - var_go_execute
  tags:
    - config_crypto-policies
    - CentOs8
    - rh8-security-features
#-------------------------------------------
- name: firewalld | CONFIGURING FIREWALLS
  import_tasks: firewalld.yml
  when: 
    - var_go_execute
  tags:
    - config_firewalld
    - CentOs8
    - rh8-security-features
#-------------------------------------------
- name: selinux | CONFIGURING SELINUX
  import_tasks: selinux.yml
  when: 
    - var_go_execute
  tags:
    - config_selinux
    - CentOs8
    - rh8-security-features
#------------------------------------------- 
- name: LinEnum | CONFIGURING File Permissions and Masks
  import_tasks: linenum.yml
  when: 
    - var_go_execute
  tags:
    - config_linenum
    - CentOs8
    - rh8-security-features
#-------------------------------------------
- name: auditd | CONFIGURING AUDITD
  import_tasks: auditd.yml
  when: 
    - var_go_execute
  tags:
    - config_auditd
    - CentOs8
    - rh8-security-features
#-------------------------------------------
- name: ObsoleteServices | Verify Obsolete Services
  import_tasks: obsolete-services.yml
  when: 
    - var_go_execute
  tags:
    - config_ObsoleteServices
    - CentOs8
    - rh8-security-features
#-------------------------------------------
- name: Generate report 
  template: 
    src: report.j2 
    dest: report.out
    owner: ransible
    group: ransible
    mode: 0640
...