---
# tasks file for roles/sec003
- name: "1.1 Copier le script posix_capabilities.sh dans /tmp -- {{ sec003 | upper }}"
  become: True
  copy:
    src: ./roles/sec003/files/posix_capabilities.sh
    dest: /tmp/posix_capabilities.sh
    owner: "ransible"
    group: "users"
    mode: 0750
#    changed_when: True
  when: >
    (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
  tags:
    - copy.script
    - copy.posix_capabilities.sh

- name: "1.2 Lancer script /tmp/cposix_capabilities.sh -- {{ sec003 | upper }}"
  become: True
  shell: "/tmp/posix_capabilities.sh"
  args:
    chdir: /tmp 
    executable: /bin/bash
#  changed_when: True
  when: >
      (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
  tags: 
    - execute.posix_capabilities.sh