---
# tasks file for roles/colsecinfo

- name: "1.1. Prérequis, Copier le script du checker"
  become: True
  synchronize:
    src: "./roles/colsecinfo/files/colsecinfo.sh"
    dest: "/tmp/"
  changed_when: False

- name: "copier script roles/colsecinfo/files/colsecinfo.sh dans /tmp"
  become: True
  changed_when: True
  when: ansible_distribution == 'CentOs' and ansible_distribution_major_version == '7'
  copy:
    src: ./roles/colsecinfo/files/colsecinfo.sh
    dest: /tmp/colsecinfo.sh
    owner: "ransible"
    group: "users"
    mode: 0750
  tags:
    - copy.script
    - copy.colsecinfo.sh

- name: "lancer script /tmp/colsecinfo.sh"
  become: True
  changed_when: True
  when: ansible_distribution == 'CentOs' and ansible_distribution_major_version == '7'
  shell: "/tmp/colsecinfo.sh"
  args:
    chdir: /tmp 
    executable: /bin/bash
  tags: 
    - execute.colsecinfo.sh